name: Build

on:
  release:
    types: [ published ]
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      nightly:
        type: boolean
        default: true
        description: "Whether to build nightly version"
      version:
        type: string
        default: v0.0.0
        description: "Version to build (e.g. v0.0.0)"

env:
  NIGHTLY_BUILD: ${{ inputs.nightly || false }}
  RELEASE_VERSION: ${{ inputs.version || github.event.release.tag_name }}

jobs:
  build-windows-x64:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.8.1'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'
          modules: 'qt5compat'
          cache: 'true'
          cache-key-prefix: 'install-qt-action'

      - name: Configure
        env:
          NIGHTLY_BUILD: ${{ env.NIGHTLY_BUILD }}
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        run: |
          mkdir build
          if ( $NIGHTLY_BUILD ){
            cmake -D NIGHTLY_BUILD=ON -D GIT_HASH=$(git rev-parse --short=7 HEAD) -S . -B build
          }
          else {
            $VER = "$RELEASE_VERSION".substring(1)
            cmake -D NIGHTLY_BUILD=OFF -D REL_VER=$VER -S . -B build
          }

      - name: Build
        run: |
          cmake --build build --target HITszConnectForWindows --config Release

      - name: Download and copy files
        env:
          VCINSTALLDIR: 'C:\Program Files\Microsoft Visual Studio\2022\Community\VC'
        run: |
          mkdir "HITsz Connect for Windows"
          cd "HITsz Connect for Windows"
          cp ../build/Release/HITszConnectForWindows.exe .
          windeployqt.exe HITszConnectForWindows.exe
          rm vc_redist.x64.exe
          curl -LO https://github.com/Mythologyli/zju-connect/releases/latest/download/zju-connect-windows-amd64.zip
          tar -xf zju-connect-windows-amd64.zip
          rm zju-connect-windows-amd64.zip
          cp ../libs/wintun/bin/amd64/wintun.dll .
          cd ..
          Compress-Archive -Path "HITsz Connect for Windows" -DestinationPath HITsz-Connect-for-Windows.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HITsz-Connect-for-Windows
          path: HITsz-Connect-for-Windows.zip

  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    needs: build-windows-x64
    steps:
      - name: Upload to release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} HITsz-Connect-for-Windows.zip
          gh release upload ${{ github.event.release.tag_name }} SHA256.txt