name: Build

on:
    release:
      types: [ published ]
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

permissions: write-all

jobs:
  build:

    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '6.5.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          modules: 'qt5compat'
          cache: 'true'
          cache-key-prefix: 'install-qt-action'

      - name: Build
        run: |
          mkdir build
          cmake -S . -B build
          cmake --build build --target ZJUConnectForWindows --config Release

      - name: Download and copy files
        env:
          VCINSTALLDIR: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC'
        run: |
          mkdir "ZJU Connect for Windows"
          cd "ZJU Connect for Windows"
          cp ../build/Release/ZJUConnectForWindows.exe .
          windeployqt.exe ZJUConnectForWindows.exe
          rm vc_redist.x64.exe
          curl -LO https://github.com/Mythologyli/zju-web-login/releases/latest/download/weblogin.exe          
          curl -LO https://github.com/Mythologyli/zju-connect/releases/latest/download/zju-connect-windows-amd64.zip
          tar -xf zju-connect-windows-amd64.zip
          rm zju-connect-windows-amd64.zip
          cp ../libs/wintun/bin/amd64/wintun.dll .
          cd ..
          Compress-Archive -Path "ZJU Connect for Windows" -DestinationPath ZJU-Connect-for-Windows.zip
          Get-FileHash ZJU-Connect-for-Windows.zip | Format-List | Out-File -FilePath SHA256.txt
          cd "C:\Program Files (x86)\Inno Setup 6\Languages"
          curl -LO https://raw.githubusercontent.com/jrsoftware/issrc/main/Files/Languages/Unofficial/ChineseSimplified.isl

      - name: Make installer
        run: |
          cd "ZJU Connect for Windows"
          curl -LO https://aka.ms/vs/17/release/vc_redist.x64.exe
          cd ..
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ZJU-Connect-for-Windows
          path: ZJU-Connect-for-Windows.zip

      - name: Upload SHA256.txt
        uses: actions/upload-artifact@v4
        with:
          name: SHA256
          path: SHA256.txt

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: ZJU-Connect-for-Windows-Installer
          path: Output/ZJUConnectForWindowsInstaller.exe

      - name: Upload to release
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} Output/ZJUConnectForWindowsInstaller.exe
          gh release upload ${{ github.event.release.tag_name }} ZJU-Connect-for-Windows.zip
          gh release upload ${{ github.event.release.tag_name }} SHA256.txt